### ISSUE TITLE
Compiler failing due to spaces in the path (it seems)

### ISSUE THREAD

**Issue by avoitishin** [blu3mania/npp-papyrus#18]
![image](https://user-images.githubusercontent.com/108185/149828821-b46147f2-ffe2-496d-87ca-41e3be509c3d.png)
![image](https://user-images.githubusercontent.com/108185/149828974-7acf0755-a0a1-4fc8-83b4-9c7be9d7d7fc.png)

Tried putting path in quotes, escaping the spaces but got the same result. Not sure what I am doing wrong

**Comment by blu3mania** [comment]
@avoitishin No, space is not the issue as the code automatically adds double quotes around the paths. The problem is actually that with the trailing blckslash for input/out directory in your settings, the command line will become
`
"E:\Games\Steam\steamapps\common\Skyrim Special Edition\Papyrus Compiler\PapyrusCompiler.exe" YourSource.psc -i="E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Scripts\Source\" -o="E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Scripts\" -f=TESV_Papyrus_Flags.flg -op
`

You see that \\" in the command at the end of "-i" and "-o" param? Almost all command line programs should be able to correctly handle it and realize it is a trailing backslash, but for some reason PapyrusCompiler.exe treats it as an escape of double quote, and thus you see the double quote at the end of "-i" part in the error message you showed above, instead of backslash. I have no idea why Bethesda implemented their tool this way but it's out of my control.

To make it work, you have 2 options. One is to remove the trailing backslash in both input and output directory settings. The other is to actually make it double backslash, e.g. `E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Scripts\Source\\`

**Comment by avoitishin** [comment]
Ah! This helped. Thank you

**Comment by blu3mania** [comment]
You are welcome! I will close this issue then.
